### ISSUE TITLE
Filtered blog results should display a sub-title

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#100]
Like, "Filtering articles by 'PhoneGap Build'"

**Comment by jahoni** [comment]
Put together an idea:

[Icon SVG](https://www.dropbox.com/s/1vmdz0iv0dpmfer/filter.svg?dl=0) | [Mock-up](https://www.dropbox.com/s/y0x8s081bjj0y11/blog-mockup.psd?dl=0) ("Filtered List" Comp)

![blog-filtered-list](https://cloud.githubusercontent.com/assets/178345/13339487/cd5dbce0-dbdd-11e5-88c0-4a82d93d4066.png)

**Comment by GarthDB** [comment]
do you want a way to remove the filter?

**Comment by GarthDB** [comment]
get back to the blog home?
