### ISSUE TITLE
App detail page pagination

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#101]
A couple of things:

The pill button should have a grey background (like what is used on the blog) because they are sitting on white:

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13193161/cf3c28d0-d728-11e5-8df2-f118d6473200.png)

Instead of "Return" I'd suggest labelling the button "App Showcase"

**Comment by GarthDB** [comment]
looks like I also need something to keep the store buttons separated.
