### ISSUE TITLE
PhoneGap Blog - Compatibility with old categories (i.e. PhoneGap Build)

### ISSUE THREAD

**Issue by wildabeast** [phonegap/phonegap.github.io#102]
The old Build blog url: http://phonegap.com/blog/phonegap-build returns a 404 -- it should forward to the new Build blog url -- but this leads to a related issue: on the old site PGB blog posts were identified by `category:build`, but I'm not seeing any obvious way to filter by category on the new site. I see the `phonegap-build` tag, but most PGB blog posts didn't utilize tags.

**Comment by jahoni** [comment]
@wildabeast Would using tags for build-related posts work (with the ability to filter by that tag), or do you feel that a category (and likely thus a fallback to the old "tabbed" approach) is required?

**Comment by GarthDB** [comment]
I think I can do it by the category that is applied automatically by being in the build directory.

**Comment by wildabeast** [comment]
@jahoni tags are fine but I guess that would mean going back through all the old Build blog posts and tagging them with phonegap-build

**Comment by jahoni** [comment]
isn't that what robots are for?

**Comment by jahoni** [comment]
The page title for the URL is "PhoneGap Day" ...should be "PhoneGap Build".

I feel like this "half" solves the issue. 
Users can't come to the blog and view Build posts by tag filtering. They can only manually enter the URL. Further, the link to the blog in the PhoneGap Build global nav goes directly to "phonegap.com/blog" now.

My suggestion is that filtering by the PhoneGap Build tag shows all build articles, and that the link from build.phonegap.com is to http://phonegap.com/blog/tag/phonegap-build/

If there is no way to tag build articles with a robot (I'm not kidding) then I will go through each build file and tag them, and suggest that all build posts be tagged correctly going forward.

**Comment by wildabeast** [comment]
awesome thanks @GarthDB. just tested an old direct article link as well, looks good (http://phonegap.com/blog/2016/02/16/git-plugins/). i'll switch the PGB link bag to the phonegap-build filter.

+1 to @jahoni's suggestion.
