### ISSUE TITLE
Blog articles not showing arrow images in footer

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#106]
Next to the links "Get Started Now" and "Read Our Blog" should have arrows next to them, for some reason not showing up on blog article pages.

Desktop:
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13197573/566f887e-d7a6-11e5-89ca-5a061d65cf52.png)

Mobile:
![img_1255](https://cloud.githubusercontent.com/assets/178345/13197578/95178a0e-d7a6-11e5-9a1d-e0fa333c79f8.JPG)

**Comment by GarthDB** [comment]
I think it was a caching issue, it's working now.
![image](https://cloud.githubusercontent.com/assets/125516/13197939/214e81b4-d7b9-11e5-8f52-e13543c55eab.png)

**Comment by jahoni** [comment]
Pretty sure it isn't a caching issue. Arrows still aren't displaying (for either desktop or on mobile devices) - I've tried multiple devices and networks.

I'm talking specifically about individual blog articles.
