### ISSUE TITLE
Remove horizontal rule at the very bottom of blog articles

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#108]
The light grey rule shouldn't be displaying (sitting right on-top of footer)

![img_1255](https://cloud.githubusercontent.com/assets/178345/13197592/1d414a46-d7a7-11e5-8875-62495a71be5b.JPG)

**Comment by GarthDB** [comment]
what about when the pagination navigation is there? 
![image](https://cloud.githubusercontent.com/assets/125516/13197949/4d576f0a-d7b9-11e5-87df-86638a1bd986.png)

**Comment by jahoni** [comment]
It is cool the have the horizontal rules on the main blog (list) page, it is the individual articles where they don't really fit.
