### ISSUE TITLE
Add code snippet styling to blog articles

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#115]
Would be great to have the same styling from docs.phonegap.com used for code snippets.

Currently:
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13230975/78bbc642-d95c-11e5-8770-a909147bb82a.png)

From docs:
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13231000/94b3eaa0-d95c-11e5-953e-8df8a7ed5c82.png)

**Comment by GarthDB** [comment]
I also was talking with @mwbrooks today - we need a style for inline code snippets in docs and the blog.
![image](https://cloud.githubusercontent.com/assets/125516/13231061/3814a600-d965-11e5-9500-560ee9a00243.png)

**Comment by jahoni** [comment]
Good call - let's use the following style for inline snippets:

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13233201/7890ddc8-d967-11e5-93f5-7f0408432749.png)

**Comment by mwbrooks** [comment]
oooooo exciting!

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/13304156/69edddb6-db10-11e5-9720-67087c4815a9.png)
