### ISSUE TITLE
Blog article videos and images blowing up on mobile devices

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#116]
Can we do anything to get both image and video assets to be responsive?

# Sample image
 from http://phonegap.com/blog/2016/01/21/rangle-guest-post/ 

![img_3610](https://cloud.githubusercontent.com/assets/178345/13231147/3e450018-d95d-11e5-8094-1918d215882f.PNG)

# Sample video 
from http://phonegap.com/blog/2016/02/18/pgday-us-2016-mind-the-gap/

![img_3609](https://cloud.githubusercontent.com/assets/178345/13231166/6015ee3c-d95d-11e5-8d1e-ee6ff907901e.PNG)

**Comment by GarthDB** [comment]
@jahoni someon forced inline styles. I'll have to see if I can work something out, otherwise we'll have to just fix them one by one.
