### ISSUE TITLE
Setup a Stickermule Account

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#12]
In order to allow people to order their own stickers, we'll need to setup a proper Stickermule account. Maybe we already have one?

**Comment by jahoni** [comment]
We don't have a team account yet. It is something that I talked to @timkim about getting set-up, though.

**Comment by mwbrooks** [comment]
Cool, I can do it as well!

**Comment by timkim** [comment]
Ya, we may as well register to something more official like phonegap@adobe.com as opposed to a personal account.

**Comment by GarthDB** [comment]
We can now reorder from different accounts on [Sticker Mule](https://www.stickermule.com/reorder)
