### ISSUE TITLE
"PhoneGap Network" tag

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#122]
We syndicate from a few blog authors (for example Simon and Holly). It would be great to have the "PhoneGap Network" tag applied to these posts, such that users can filter by that tag in the sidebar, and also beneath the title of articles. 

(Currently there appear to be no tags associated with PhoneGap Network articles)

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13268183/e982e8ae-da35-11e5-8435-cde40c367c3d.png)

**Comment by GarthDB** [comment]
Would you like some visual affordance to indicate the post is different and taking the user away from the site?

**Comment by jahoni** [comment]
nope
