### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#129]
Having tests fail on every build helps no one. It simply hides real failures.

Let's disable to the tests that fail (broken links), until we can spend more time on it.

**Comment by GarthDB** [comment]
@mwbrooks sounds good. We could still run the basic test to find out if it is building without errors. Then sort out the links test later.

**Comment by mwbrooks** [comment]
Done

**Comment by GarthDB** [comment]
:+1: :shipit:
