### ISSUE TITLE
Blog articles should provide a link to blog home

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#130]
Somewhere near the title, likely kinda like a breadcrumb

**Comment by GarthDB** [comment]
Agreed.

**Comment by jahoni** [comment]
Put something together, should be pretty quick to implement.

[Icon](https://www.dropbox.com/s/azlgaiyp4b5xmka/tiny-arrow-left.svg?dl=0) | [Mock-up](https://www.dropbox.com/s/y0x8s081bjj0y11/blog-mockup.psd?dl=0) ("Article" Layer Comp)

![blog-article](https://cloud.githubusercontent.com/assets/178345/13338793/ab75f016-dbd8-11e5-880a-2d75dfa7a911.png)
