### ISSUE TITLE
Split Blog to it's own repo

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap.github.io#134]
I'm thinking this would be a good idea, mostly because it would allow us to speed up the rendering of both. The main pages would be dramatically faster, including the base css used by all the sub page repos.

**Comment by GarthDB** [comment]
Curious if you see anything wrong with splitting it up @mwbrooks ?

**Comment by mwbrooks** [comment]
Not that I can think of, especially since app is already showing the technical-side of splitting it up. It may be easier for people writing / previewing blog posts as well.

**Comment by GarthDB** [comment]
I fixed all the tests, now I just need to add the latest posts to the new repo and adjust the readme files.
https://github.com/phonegap/reblog
