### ISSUE TITLE
Styling of headers in blog content inconsistent

### ISSUE THREAD

**Issue by wildabeast** [phonegap/phonegap.github.io#135]
Headers rendered using pound / hash like so:

```
## Header 1
### Header 2
```

are styled inconsistently. The first shows up with all caps no bold, the second is camel case and bolded, and both are the same font size. [Example here](http://phonegap.com/blog/2016/02/24/phonegap-build-confg-xml-now-required-and-other-updates/).

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/13409576/d3562bda-def0-11e5-826c-20445a652973.png)

I'll update it to this.

**Comment by wildabeast** [comment]
cool thanks. if its a matter of me just selecting the wrong heading type, thats cool too just let me know. prolly worth adding to the blog posting guidelines if not already in there.

**Comment by GarthDB** [comment]
so the headline is already an `h1`, so maybe always start with an `h2`?

**Comment by jahoni** [comment]
Yeah - from the mock-up:

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13410251/821e69f8-deeb-11e5-8d9f-9dbce30a31da.png)

...where in-article sub-headings being with H2
