### ISSUE TITLE
Add SF meetups to events page

### ISSUE THREAD

**Issue by jenlgray** [phonegap/phonegap.github.io#137]
1. Remove PhoneGap Spain meetup from the page

2. Add:

- March 18th - http://www.meetup.com/sfhtml5/events/228341183/
Learn about Mobile Design and Development with Adobe's Project Comet and PhoneGap from Vincent Hardy, Demian Borba, and Garth Braithwaite. 

- March 28th - http://www.meetup.com/PhoneGap-SF/events/229337811/
Join us at the official San Francisco PhoneGap meetup group to hear from the PhoneGap team and the Monaca X Onsen UI teams.

**Comment by jahoni** [comment]
Hey @jenlgray - doesn't look like @GarthDB was able to get to this, and these events are now (or very soon to be) in the past, too. What, if anything, should we be putting on this page?

**Comment by jenlgray** [comment]
@jahoni Just PhoneGap Day EU and events from meetup/lanyrd if we can pull those in.
