### ISSUE TITLE
Feature request: ability to filter blog posts by author

### ISSUE THREAD

**Issue by wildabeast** [phonegap/phonegap.github.io#138]
Something like http://phonegap.com/blog/author/john-doe/ would be nice.

**Comment by jahoni** [comment]
sounds like a good idea to me, adding to the Phase II milestone.

**Comment by GarthDB** [comment]
I added the author pages, it does make the build time longer (each page loops through all the posts to filter them). We could probably ignore a ton of authors in the page generating script.

**Comment by GarthDB** [comment]
Closing for now, feel free to reopen if we need to tweak further. http://phonegap.com/blog/author/ryan-willoughby/

**Comment by jahoni** [comment]
A suggestion/question: might it make sense to make the author's name a link and/or add a list of authors to the right sidebar (beneath tags) so that one can actually get to the author URL?

**Comment by GarthDB** [comment]
Sure.
