### ISSUE TITLE
Cordova Error: Please install Android target: “android-23”: PhoneGap :6.0.1

### ISSUE THREAD

**Issue by dinesh-1992** [phonegap/phonegap.github.io#139]
I am trying to build apk with Phonegap 6.0.1 at path
`/path/to/myproject/platforms/android/cordova`
run command `build --release` get error as below
`CordovaError: Please install Android target: "android-23".`

Stackoverflow question with more details : [Here](http://stackoverflow.com/questions/36053007/cordova-error-please-install-android-target-android-23-phonegap-6-0-1)

Thank in advance for help

**Comment by wildabeast** [comment]
Hi, this repository is just for issues with the phonegap.com website. Please try:

https://groups.google.com/forum/#!forum/phonegap
https://forums.adobe.com/community/phonegap
