### ISSUE TITLE
Create About / FAQ Page

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#14]
Create the first pass of the About / FAQ page.

**Comment by jahoni** [comment]
@jenlgray - can you review the content currently at http://phonegap.com/about/faq/ and make any necessary changes, please?

**Comment by jahoni** [comment]
I'm not sure this is ready to be closed yet - I'd like to see the FAQs reviewed/updated.

**Comment by GarthDB** [comment]
This was the initial creation, I'll open a new issue and assign it to @jenlgray to review it.

**Comment by jahoni** [comment]
sounds good. thanks

**Comment by mwbrooks** [comment]
![screen shot 2016-01-15 at 3 12 01 pm](https://cloud.githubusercontent.com/assets/21328/12367852/9f631eba-bb9a-11e5-9a84-6dd2b78e5c92.png)
