### ISSUE TITLE
PhoneGap CLI install option should appear below the Mac / Win download links

### ISSUE THREAD

**Issue by davejohnson** [phonegap/phonegap.github.io#147]
something along these lines ... except better

![screen shot 2016-04-08 at 11](https://cloud.githubusercontent.com/assets/2680/14393552/678a4f8a-fd7c-11e5-9d80-84d891d78223.png)

**Comment by jahoni** [comment]
i'll mock something up.

**Comment by jahoni** [comment]
Okay, a mock-up (with a new [icon](https://www.dropbox.com/s/7o6zgey05syh0t1/command.svg?dl=0)):

[PSD](https://www.dropbox.com/s/dbpslus9lp76xq1/getstarted-mockup.psd?dl=0) | PNG:

![getstarted-desktop_0001_normal-short](https://cloud.githubusercontent.com/assets/178345/15374387/fefa8c08-1cfe-11e6-911f-11914f9d63c8.png)
