### ISSUE TITLE
Integrate web site performance results to workflow

### ISSUE THREAD

**Issue by davejohnson** [phonegap/phonegap.github.io#162]
It would be great to see results from something like YSlow that are run on commits / publishes to track performance and make sure we are inline with current best practices.

**Comment by GarthDB** [comment]
google pagespeed insights

**Comment by GarthDB** [comment]
It definitely could be done using [this](https://github.com/addyosmani/psi/). Now we should just figure out what pages we should target for these tests.

**Comment by purplecabbage** [comment]
Hi Dave!
