### ISSUE TITLE
Fix notifications

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap.github.io#168]
Save @timkim from the flood of emails by switching to slack notifications for travis status.
![emails](https://cloud.githubusercontent.com/assets/125516/19749746/b4211fca-9ba8-11e6-9e5d-4c720855e318.gif)

- [x] phonegap/phonegap.github.io
- [x] phonegap/blog
- [x] phonegap/app
- [x] phonegap/book
- [x] phonegap/tool
- [x] phonegap/phonegap-docs

**Comment by alharding** [comment]
@timkim just needs to setup some Outlook filtering... 10k+ unreads!! ;)

**Comment by GarthDB** [comment]
It would be nice to have better slack handling of this stuff, it's fine.
