### ISSUE TITLE
Create 404 Page

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#17]
Create the first pass at the 404 page. Man, I hope we can do some fun 404 pages!

**Comment by jahoni** [comment]
Moving this into "Phase II".

**Comment by jahoni** [comment]
I lied, putting it back into Phase I. Mock-up is at
https://www.dropbox.com/s/43uovo07i5ld52j/404.psd?dl=0

![404](https://cloud.githubusercontent.com/assets/178345/12858977/15d05374-cc08-11e5-878b-42cbb273d8de.png)
