### ISSUE TITLE
Fix SSL on phonegap.com

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#176]
![image](https://cloud.githubusercontent.com/assets/21328/20981369/4e04ddd0-bc69-11e6-9c83-516cc5da9365.png)

This is a regression from the old design which supported SSL.

**Comment by GarthDB** [comment]
We could fix this with CloudFlare - the free plan would be enough and do a lot for performance as well. Any objections @mwbrooks? Anyone else I should check with?

**Comment by alharding** [comment]
@GarthDB I was thinking we could use Azure also. There is an auto-deploy from Github to Azure we can do on commits to a specific branch and then we have all of the Azure scaling we can leverage.

**Comment by GarthDB** [comment]
@alharding azure could work, but seems like a more complex solution. The nice part of the gh-pages is whatever is in the repo (on master) is live. CloudFlare just does things on the DNS level, not on the actual hosting.

**Comment by GarthDB** [comment]
Azure or something like it might be a good solution for the blog complexity if we want to keep using jekyll there.

**Comment by alharding** [comment]
@GarthDB We could have it configured _really_ quickly. Still need to address the SSL certificate so not sure if or how github pages can do that? It's really straight forward as an azure website though... and same thing also in regards to whatever is in the repo would be live. We just configure which branch we want to be live (in this case master) and it would deploy to Azure after any commit to that branch.

**Comment by GarthDB** [comment]
CloudFlare has free ssl support https://www.cloudflare.com/ssl/

**Comment by mwbrooks** [comment]
@GarthDB The blog is a whole different topic, so I would avoid having it influence the decision.

I know Cloudflare is a very common solution and is a quick and transparent fix. Azure is switching out the backend from Github Pages or Azure. I've never used it, so I can't weigh in on whether it's worth it or not.

**Comment by alharding** [comment]
If CloudFlare is quick and simple let's do that and get that fixed up. We can approach the Azure topic at a later time.

**Comment by GarthDB** [comment]
ok. I'm on it.

**Comment by mwbrooks** [comment]
@GarthDB any progress on this? Thoughts on using Cloudflare until the new year when we can revisit this. Would switching to Cloudflare and then to Azure afterward be troublesome?

**Comment by purplecabbage** [comment]
Resolved
