### ISSUE TITLE
First Pass of Homepage Implementation

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#2]
Let's use this issue to track and implement the first pass at the implementation of the homepage design.

Feel free to comment here as the implementation progresses: http://phonegap.github.io/

**Comment by GarthDB** [comment]
screenshots help.
![homepage-desktop_0000_normal](https://cloud.githubusercontent.com/assets/125516/8298645/7deb2c24-1928-11e5-9bed-a75285a93583.png)

**Comment by mwbrooks** [comment]
:D

**Comment by chrisgriffith** [comment]
Had some visual trouble with the robot feet. I felt i needed to see more leg to make the visual connection.  The portion of the robot that is behind the panel is almost too close in color to the panel.

**Comment by chrisgriffith** [comment]
Thought the PG logo and the top level menu element should be on the solid bg, and not allow for elements to appear under them making it harder to see.

**Comment by GarthDB** [comment]
@chrisgriffith - yeah, it's not done. I'll file a new issue for it.
![image](https://cloud.githubusercontent.com/assets/125516/8601703/f8f0d252-262a-11e5-9005-c4c4cffb0d47.png)

**Comment by GarthDB** [comment]
Done.

**Comment by mwbrooks** [comment]
Yay! Nice work!
