### ISSUE TITLE
Create Products Page

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#21]
Create the first pass at the Products page.

**Comment by jahoni** [comment]
Waiting for CLI blurb from @mwbrooks and/or @hollyschinsky, in the meantime the [mock-up](https://www.dropbox.com/s/mnz8lyudp1rm1ig/products.psd?dl=0) looks like this:

![products](https://cloud.githubusercontent.com/assets/178345/12499316/5203d394-c05e-11e5-836d-3e35dbe35eed.png)

**Comment by jahoni** [comment]
Cool - the first pass at Product content is ready for initial launch, and I've updated the [mock-up](https://www.dropbox.com/s/mnz8lyudp1rm1ig/products.psd?dl=0) to include CLI copy.

Refer to the [Google Doc](https://docs.google.com/document/d/1L9nB5IJRUeE1AV_KUt99v16SIvOqhdgeRjekOjqruCk/edit?usp=sharing) for full copy/links.
