### ISSUE TITLE
Home page hero/sub-hero: rework for "hand" size

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#27]
I'd love to see the hero and sub-hero sections on the homepage look more awesome on small(erest) screens.

Main edits/additions:
* Keep robit visible at all sizes if possible, scaling and moving to accommodate
* Add spacing and horizontal rule to sub-hero sections.

#### (non-retina PNG)
![home-hero-hand](https://cloud.githubusercontent.com/assets/178345/11200727/10cfb8c0-8c8d-11e5-8e91-e29dfc5ae324.png)

#### (retina PNG)
![home-hero-hand-retina](https://cloud.githubusercontent.com/assets/178345/11200923/877b030c-8c8e-11e5-83a0-ab8825913c13.png)

## Current implementation
![img_3328](https://cloud.githubusercontent.com/assets/178345/11201000/14bf696a-8c8f-11e5-909d-9847561a98b4.png)

**Comment by jahoni** [comment]
The hand size looks great, but the Robit is now sitting (too) far left at large screen sizes (930 px and above)

#### Safari
![image](https://cloud.githubusercontent.com/assets/178345/11229005/1d8449a0-8d46-11e5-9145-83f08a98607c.png)

#### Chrome
![image](https://cloud.githubusercontent.com/assets/178345/11229020/3977dfe6-8d46-11e5-8c64-12ddabe5dca1.png)

**Comment by jahoni** [comment]
Looks like it isn't just on the desktop - below are screenshot from iPad mini...

#### Safari (iOS 9.1, iPad mini)
![img_0087](https://cloud.githubusercontent.com/assets/178345/11229105/12e7fad6-8d47-11e5-8cbd-def749453635.PNG)

#### Chrome (iOS 9.1, iPad mini)
![img_0087](https://cloud.githubusercontent.com/assets/178345/11229112/196e1e4e-8d47-11e5-8dfb-7dfa17694e5c.PNG)

**Comment by GarthDB** [comment]
sorry, it was a negative margin I added in the lower media query that I didn't remove in the larger one. Fixed now, just waiting for the changes to publish.

**Comment by jahoni** [comment]
Awesome. looks good now. no sorries necessary. thank for the fix.

**Comment by GarthDB** [comment]
Just trying to speak Canadian.
Thanks for catching it.
