### ISSUE TITLE
Home page hero/sub-hero: rework for "big hand" (tablet horiz) size

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#28]
Currently, at 820px, the header/global navigation switches from "mobile" to "desktop" (I like to use quotation marks) - but the hero layout stays 1 column until 930px width.

#### Mobile nav with hero layout, below 820px width
![image](https://cloud.githubusercontent.com/assets/178345/11229213/05df11de-8d48-11e5-9d4a-a37525e4705e.png)

#### Mobile nav with hero layout, 820px to 930px width
![image](https://cloud.githubusercontent.com/assets/178345/11229247/67b27158-8d48-11e5-8e62-fa8189d12d2e.png)

### Ask

It'd be sweet if the layout could switch to displaying the Robit to the left of the hero text, but with a slightly reduced sized Robit (~ 80% of full size?), from 820px to 1060px (where the Robit image does not interfere with readability of hero text). 

Honestly - I'm not sure about reducing the size of the Robit, but definitely about swaping the layout.

**Comment by GarthDB** [comment]
How about this?
![image](https://cloud.githubusercontent.com/assets/125516/11234061/98d567c0-8d81-11e5-9ffe-91b813ec4a84.png)

**Comment by jahoni** [comment]
YAASS!

**Comment by GarthDB** [comment]
alright, calling this closed. It's live, if you have any more changes we can reopen it.
