### ISSUE TITLE
Get Started: reduce spacing between steps at on hand sizes

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#29]
Let's reduce the amount of vertical space between steps on smaller screen sizes, likely by about 20px.

#### Currently (iOS, Chrome)

![img_3336](https://cloud.githubusercontent.com/assets/178345/11254454/a7ccd44c-8df5-11e5-9311-327379eb2e88.PNG)

**Comment by GarthDB** [comment]
![image](https://cloud.githubusercontent.com/assets/125516/11262883/b88551a0-8e41-11e5-806d-e53d38478305.png)
