### ISSUE TITLE
Create App Showcase Page

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#31]

**Comment by jahoni** [comment]
Okay - mock-up feels pretty solid. 

A quick walk-through:

* Noteworthy apps are likely also "featured" apps, but ones that we really want to highlight. They'd likely be the ones shown on the homepage, as well.

* Featured apps are ones that we flag as being particularly good. The list should display by date added.

* I've made room for "enterprise" apps, but not sure that that will be populated for awhile?

* I would love it if we could somehow add search functionality, but that can come at a later date. For now, I've just included the ability to narrow by platform.


![appshowcase](https://cloud.githubusercontent.com/assets/178345/11673018/32bc8b0e-9dca-11e5-9659-3ae83e8bc2d4.png)

**Comment by GarthDB** [comment]
Thanks so much @jahoni

**Comment by jahoni** [comment]
I neglected to add the ability to submit apps in the previous comp, so the [mock-up](https://www.dropbox.com/s/ajrhykipwrobxmm/appshowcase.psd?dl=0) has been updated.

There are now three places links to that action: in the page title/description, as a pill button in the filter bar, and in the app showcase specific footer.

![appshowcase](https://cloud.githubusercontent.com/assets/178345/11796986/affc7d82-a274-11e5-9548-01f1fac75677.png)

**Comment by jahoni** [comment]
I edited to mock-up again, to remove "Enterprise" as a filter for apps.

![babybeaver](https://cloud.githubusercontent.com/assets/178345/12310753/db5b19a8-ba06-11e5-981f-09a20e90801b.jpg)

Oops! Wrong picture. *This* is the mock-up.

![appshowcase](https://cloud.githubusercontent.com/assets/178345/12310776/f92c0546-ba06-11e5-9e8a-f9939e0da227.png)

**Comment by GarthDB** [comment]
Making progress
![image](https://cloud.githubusercontent.com/assets/125516/12505424/168a045a-c0a4-11e5-9e7b-d51f3d84f4f3.png)

**Comment by mwbrooks** [comment]
Nice!

**Comment by GarthDB** [comment]
@jahoni So I got it working, but do we still want to have the noteworthy app section?
![image](https://cloud.githubusercontent.com/assets/125516/13178466/4121bc64-d6dc-11e5-9e7a-c790998d9ed2.png)
