### ISSUE TITLE
Create App Detail Page

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#35]

**Comment by jahoni** [comment]
Created a mock-up (desktop version). [PSD (layer comp: app detail) is here] (https://www.dropbox.com/s/ajrhykipwrobxmm/appshowcase.psd?dl=0).

![appshowcase-appdetail](https://cloud.githubusercontent.com/assets/178345/12365402/775d0950-bb89-11e5-9e9a-5248f8647d63.png)

**Comment by GarthDB** [comment]
I didn't do the modal for now. For a couple of reasons but mostly the mobile and deep linking.

![image](https://cloud.githubusercontent.com/assets/125516/13184162/849ce99e-d6f7-11e5-9cc0-92fdc0eb4ed1.png)
