### ISSUE TITLE
Add current page indication (underline) to global nav

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#44]
Add an underline to current page (for sub-pages) to global nav.

Sample mock-up:

![getstarted-desktop_0001_normal-short](https://cloud.githubusercontent.com/assets/178345/12283104/a903d1f6-b958-11e5-8c3a-9f51e1f2e32f.png)

**Comment by mwbrooks** [comment]
![screen shot 2016-01-15 at 3 10 39 pm](https://cloud.githubusercontent.com/assets/21328/12367859/ac03a8f6-bb9a-11e5-9c79-219040243765.png)
