### ISSUE TITLE
Review About / FAQ Page

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap.github.io#45]
@jenlgray could you review the About and FAQ page contents?

**Comment by GarthDB** [comment]
Here are the urls
- http://phonegap.github.io/about/
- http://phonegap.github.io/about/faq/

**Comment by jenlgray** [comment]
Looks great! Few things:

About
1. Is there a graphic after "Wrap your app with PhoneGapDeploy to mobile platforms!"? Missing some punctuation in that sentence as well.
2. Punctuation - Build your app with web technology. Wrap your app with PhoneGap. Deploy to mobile platforms!
3. Did we decide to get rid of the video? We don't really have anything else to replace it with tho
4. Update the PGB image to the new one here: https://build.phonegap.com/ that only shows iOS, Android and Windows

FAQ
1. PhoneGap is an open source implementation of open standards and is FREE. That means developers and companies can use PhoneGap for mobile applications that are free, commercial, open source, or any combination of these.
2. A: Join the PhoneGap Adobe forum here: https://forums.adobe.com/community/phonegap, follow us on Twitter or Facebook or check out the PhoneGap IRC channel on freenode. Code contributors should also check out cordova.io
3. Do we have to include the part about "Will Apple reject my PG app"?

**Comment by jahoni** [comment]
Closing this issue, and created two new ones (issue #82 and issue #81) to address content changes for each page (Project Overview and FAQs).
