### ISSUE TITLE
Fix missing image on the project overview page

### ISSUE THREAD

**Issue by GarthDB** [phonegap/phonegap.github.io#46]
I borked it, I should fix it.

![image](https://cloud.githubusercontent.com/assets/125516/12307553/3f26278e-b9fd-11e5-9255-305c3ae7fc06.png)

**Comment by GarthDB** [comment]
scraping this since @jahoni is designing a new page.

**Comment by jahoni** [comment]
Well, not exactly redesigning the page, but will rework the content. See issue #81
