### ISSUE TITLE
Remove PhoneGap Enterprise from sub-hero, replace with PhoneGap Build

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#47]
It's now rebranded as part of AEM Apps we do not need to reference it on phonegap.com

Chat with @jenlgray for more detail.

**Comment by jahoni** [comment]
Need to remove reference to PhoneGap Enterprise from homepage (sub-hero, feature grid), and consider replacement content/revised layout to incorporate changes.

**Comment by jahoni** [comment]
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/12498901/d61c54b6-c05a-11e5-8e5b-928e5de77f99.png)

New copy should read:

Package your app in the cloud
PhoneGap Build takes the pain out of compiling PhoneGap apps. Get app-store ready apps without the headache of maintaining native SDKs. Our PhoneGap Build service does the work for you by compiling in the cloud.

"Find out more" (pill button)

----
For Feature grid changes, refer to http://github.com/phonegap/phonegap.github.io/issues/71

**Comment by jahoni** [comment]
I should have said: the "Find out more" button should link to build.phonegap.com

**Comment by GarthDB** [comment]
@jahoni sorry I missed that - fixed.
