### ISSUE TITLE
Sub-headings for page titles

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#49]
Need to create for:

FAQs
License
Project Overview
Logo

**Comment by GarthDB** [comment]
yup - any recommendations?

**Comment by jahoni** [comment]
this is why it is currently assigned to me - i'll put some together, and post here.

**Comment by GarthDB** [comment]
Ah, ok here are my terrible recommendations that will motivate someone to write something better:

FAQ | We get these all the time.
License | Keeping it open.
Project Overview | What it's all about
Logo | Here be buildbots.

**Comment by jahoni** [comment]
Not bad. Here are my suggestions:

FAQs | Find the answers to things we get asked all the time.
License | Keeping it open with Apache 2.
Project Overview | A high-level summary of what PhoneGap is all about.
Logo | Download the official artwork for your favourite open source project.

Related to "Logo", I think we need to get rid of all those old buildbots (as cool as they are) and replace with the actual PhoneGap logo. I'll create a new issue related to this.

**Comment by GarthDB** [comment]
Sounds great. I'm putting them in until we get something better.
