### ISSUE TITLE
Facebook: Edit profile picture and other background thingo to new style

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#52]
![image](https://cloud.githubusercontent.com/assets/178345/12368255/7bb72f0c-bb9e-11e5-8449-bb2d14643679.png)

**Comment by jahoni** [comment]
Assets are created/located in: https://www.dropbox.com/sh/3co6s60k4z7wq4t/AACfo8F2xr9SUOjH5lHaMll4a?dl=0

I don't have admin access to make changes - so I'll leave that to @jenlgray

**Comment by jenlgray** [comment]
Updated

**Comment by jahoni** [comment]
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/12495635/b5c96bdc-c045-11e5-94de-62d9bb53a587.png)
