### ISSUE TITLE
Logo page needs actual PhoneGap logo

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#58]
black and reverse, horizontal and vertical.

**Comment by jahoni** [comment]
PNG and SVG

**Comment by GarthDB** [comment]
Do we have any special versions of the files ready for release?

**Comment by GarthDB** [comment]
wait, you assigned it to you, nevermind; I'll leave this to you @jahoni

**Comment by jahoni** [comment]
Okie dokie, I'm thinking we just link to download to this compressed archive from the footer, rather than having a page: 

[PhoneGap-Logo.zip](https://github.com/phonegap/phonegap.github.io/files/101380/PhoneGap-Logo.zip)

**Comment by jahoni** [comment]
Actually, let's keep the page...look at a layout.

**Comment by jahoni** [comment]
Okay - [Mock-up](https://www.dropbox.com/s/v8xf4cj4w6we1h8/logo.psd?dl=0) is done, need to create a few assets before I reassign the issue.

![logo](https://cloud.githubusercontent.com/assets/178345/13093790/f2d3a21a-d4bb-11e5-99e2-b5828b72839d.png)

**Comment by jahoni** [comment]
Alright, so I've updated the full set (zipped archive) and also included the SVGs to use on the page layout here: https://www.dropbox.com/sh/o5kxjub3afvsse0/AADvynXYuix5qzquLDLPWW-6a?dl=0

Like I've said, I'm okay if we need to launch with just a link to the zipped archive for Phase I (Feb 19).

[FullSet-PhoneGap-Logo.zip](https://github.com/phonegap/phonegap.github.io/files/135377/FullSet-PhoneGap-Logo.zip)
