### ISSUE TITLE
Links in front page "Dig into documentation" don't link to the docs site

### ISSUE THREAD

**Issue by devgeeks** [phonegap/phonegap.github.io#64]
![image](https://cloud.githubusercontent.com/assets/554999/12468517/93a52bde-c038-11e5-8963-6b41877c2b90.png)

**Comment by devgeeks** [comment]
Same is true of the tiles below the "Reap the benefits of open source" section:

![image](https://cloud.githubusercontent.com/assets/554999/12468898/a772344c-c03b-11e5-9413-57a2332c313e.png)

**Comment by jahoni** [comment]
For the "pre-header" documentation section, the copy should be edited to read:

Whether you’re looking for [in-depth guides] (http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/) on how to get started creating PhoneGap apps or [helpful references] (http://docs.phonegap.com/references/desktop-app/) for using the PhoneGap tools, this is the place to go. How could you go wrong?

(actual links included).

**Comment by GarthDB** [comment]
@alharding it's in https://github.com/phonegap/phonegap.github.io/blob/master/index.html
and
https://github.com/phonegap/phonegap.github.io/blob/master/_includes/footer.html

**Comment by jahoni** [comment]
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/12496987/ecbd7f90-c04d-11e5-8acd-bdaeba1bf96c.png)

footer is updated, moving "tools and benefits" to a new issue
