### ISSUE TITLE
Minor issue: On certain viewports, the "Dig into Documentation" section could use more whitespace on the margins

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap.github.io#66]
On iPhone 6s and below, it looks a bit cramped.

See:
![screen shot 2016-01-20 at 5 42 19 pm](https://cloud.githubusercontent.com/assets/36107/12469031/52fa898a-bf9d-11e5-8586-d0db2ce1f2a6.png)

**Comment by GarthDB** [comment]
Good call.

**Comment by GarthDB** [comment]
I gave it a little padding.
![image](https://cloud.githubusercontent.com/assets/125516/12505296/b882339c-c0a2-11e5-9910-3f31c0eb9d9b.png)
