### ISSUE TITLE
Minor issue: On certain viewports, the "Learn More" link is broken into two lines

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap.github.io#67]
iPhone 5s and below. Not sure if this is even fixable, minor nitpick.

See:
![screen shot 2016-01-20 at 5 49 57 pm](https://cloud.githubusercontent.com/assets/36107/12469182/680c328c-bf9e-11e5-9806-4903acbe75b7.png)

**Comment by GarthDB** [comment]
Looks like your scroll bars are causing that issue.
![image](https://cloud.githubusercontent.com/assets/125516/12505238/29a32e24-c0a2-11e5-9bbb-5456c0cc1783.png)

**Comment by GarthDB** [comment]
Looks like you scrollbars might be causing it @shazron 
![image](https://cloud.githubusercontent.com/assets/125516/12505244/418cc702-c0a2-11e5-8da9-8cfbf4f39ae7.png)

**Comment by shazron** [comment]
Heh bug in their tool I guess :)
