### ISSUE TITLE
Newsletter sign up in footer - no form submit feedback

### ISSUE THREAD

**Issue by alharding** [phonegap/phonegap.github.io#69]
There is no feedback to the user that they are subscribed to the email newsletter. It doesn't look like the form is correctly posting the data anywhere.

![screen shot 2016-01-21 at 1 14 06 pm](https://cloud.githubusercontent.com/assets/926204/12494753/de28002a-c040-11e5-96d3-9952b132e522.png)

**Comment by jahoni** [comment]
Where are these emails/signups to be sent to @jenlgray?

**Comment by jenlgray** [comment]
Campaign Monitor:

<img width="1163" alt="screen shot 2016-01-21 at 3 31 00 pm" src="https://cloud.githubusercontent.com/assets/9487317/12496610/0d94d24e-c054-11e5-9699-15d485c5b515.png">

**Comment by jenlgray** [comment]
might want to test it first to make sure the signups are getting pumped into Campaign Monitor

**Comment by GarthDB** [comment]
@jenlgray can you get me the url for the form? I can copy the info and make this for work.

**Comment by jenlgray** [comment]
Yes, doing some research. Not quite sure where to find that. Sent a support email to Campaign Monitor.

**Comment by GarthDB** [comment]
What's the url of the page you took the screenshot - I can build it from that.

**Comment by jenlgray** [comment]
5. There, you'll be provided with the HTML to add a simple sign up form to your website's HTML. However, if you already have your own custom coded sign up form, then you'll just want to grab the list's information to enter into your own form's HTML.

Specifically, you'll want to grab the list's URL, which would look something like: http://example.createsend.com/t/t/s/oykitu/

Then, you'd want to grab the email parameter as well. It'd look something like: 

<p>
<label for="fieldEmail">Email</label><br />
<input id="fieldEmail" name="cm-oykitu-oykitu" type="email" required />
</p>

This is the code I got from Campaign Monitor:

<form action="http://nitobi.createsend.com/t/y/s/htjuyh/" method="post" id="subForm">
    <p>
        <label for="fieldName">Name</label><br />
        <input id="fieldName" name="cm-name" type="text" />
    </p>
    <p>
        <label for="fieldEmail">Email</label><br />
        <input id="fieldEmail" name="cm-htjuyh-htjuyh" type="email" required />
    </p>
    <p>
        <button type="submit">Subscribe</button>
    </p>
</form>

**Comment by jahoni** [comment]
Use what is on the current site
