### ISSUE TITLE
Tools & benefits section of homepage: update content, add hyperlinks

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#71]
currently:

![image](https://cloud.githubusercontent.com/assets/178345/12497025/27f57ea0-c04e-11e5-82e3-fee12d30fa77.png)

need to take out PhoneGap Enterprise, and add correct hyperlinks.

**Comment by alharding** [comment]
@jahoni How should it look with 5 for wrapping? 


Looks ok on smaller screens when it is a row of 2, 2, 1:
![screen shot 2016-01-21 at 2 58 58 pm](https://cloud.githubusercontent.com/assets/926204/12497264/9553dc98-c04f-11e5-8c27-386615b5511a.png)

But wider desktop screen: 
![screen shot 2016-01-21 at 2 59 11 pm](https://cloud.githubusercontent.com/assets/926204/12497266/9b64f5cc-c04f-11e5-8bee-892656b7fcdb.png)

**Comment by jahoni** [comment]
we're not using 5. we're using 6.

**Comment by alharding** [comment]
k, is something replacing the PGE item that gets taken out then?

**Comment by jahoni** [comment]
dude, you need to chill. i'm working on the mock-up with new copy, and icons. when it is ready for implementation, i'll post those here and reassign the issue.

**Comment by alharding** [comment]
No worries, I didn't know a new mock-up was on the way.

**Comment by jahoni** [comment]
[Mock-up](https://www.dropbox.com/s/m2101j7we15tnbh/homepage-mockup.psd?dl=0) snippet:

![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/12499122/ab39ba52-c05c-11e5-9279-a58edf34ab27.png)

Run down of changes:

- remove PhoneGap Enterprise, replace with PhoneGap Build
- change PhoneGap Developer apps to PhoneGap Desktop : Our desktop app is the snappiest way to create new PhoneGap apps without using the command line.
- add PhoneGap Developer: Use our mobile app to connect your devices to your development machine, then see the changes you make instantly.
- new icons [magic](https://www.dropbox.com/s/rp1b88e72q40imm/magic.svg?dl=0) and [bolt](https://www.dropbox.com/s/a8gen119n38h3r4/bolt.svg?dl=0). I used the new (to me) Illustrator "export" tool to save the SVGs...not sure how that'll work out, haven't tested.

----

In the event that "Third Party Tools" is not going live for initial launch, remove the entire second row (Plugin Library, Third Party Tools, and Developer Community) until that is available.

**Comment by jahoni** [comment]
Links should be as follows:

PhoneGap Desktop: (no URL yet), but to "PhoneGap Desktop" anchor link on product page.
PhoneGap Developer: (no URL yet), but to "PhoneGap Developer" anchor link on product page.
PhoneGap Build: http://build.phonegap.com

Plugin Library: http://cordova.apache.org/plugins/
Third Party Tools: (no URL yet), but to Third Party tools page when it gets created
Developer Community: https://forums.adobe.com/community/phonegap
