### ISSUE TITLE
Featured Apps for launch

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#79]
Determine the list of apps that we want to feature on the site for launch, using https://docs.google.com/spreadsheets/d/1jBaPzonCztoiuKWTZ-OTm8Zu_Akn0zWlaYO_Y2vFUi8/edit?usp=sharing as a starting point

**Comment by GarthDB** [comment]
@jenlgray made the list:

- [HealthTap](https://www.healthtap.com/)
- [Hockey Community](http://hockey-community.com/)
- [Bit Timer](http://www.bittimerapp.com)
- [snowbuddy](http://snowbuddyhq.com/)
- [Untappd](http://untappd.com)
- [BrowserQuest](http://mpbrun.dk/)
- [METAR Reader](http://www.metarreader.com/app)
- [Logitech Squeezebox™ Controller](http://www.logitech.com/en-us/speakers-audio/wireless-music-systems/devices/7979)
- [TripCase](http://travel.tripcase.com/)
- [My Heart Camera](http://apmaga.heteml.jp/_app/heartcamera/)
- [Yoga+Travel](http://www.yogabyallison.com/www/index.php?/default/action/products/)
- [Sworkit](http://sworkit.com)

**Comment by jahoni** [comment]
Reopening to correct some outdated apps

**Comment by GarthDB** [comment]
:+1:

**Comment by jahoni** [comment]
Correct order (by date of submission) of apps with URL and markdown (or HTML) file reference:

Localeur
- http://phonegap.com/app/localeur/
- 2015-11-12-localeur.md
- need to update our icon to the most current, here:
http://a4.mzstatic.com/us/r30/Purple49/v4/62/fc/2f/62fc2fd2-0ac6-0592-c93f-5e8a3a286004/icon175x175.png
- can't figure out why we are showing outdated screenshots (don't match what is in the app stores)....

Sworkit:
- http://phonegap.com/app/sworkit/
- 2015-06-11-sworkit.md

snowbuddy: 
- http://phonegap.com/app/snowbuddy/
- 2015-06-10-snowbuddy.md

BrowserQuest
- http://phonegap.com/app/browserquest/
- 2013-08-12-browser-quest.md

Yoga+Travel
- http://phonegap.com/app/yoga-travel/
- 2013-06-29-yoga-travel.md

My Heart Camera
- http://phonegap.com/app/my-heart-camera/
- 2013-06-24-my-heart-camera.md
- need to update our icon to the most current, here: http://a4.mzstatic.com/us/r30/Purple3/v4/5c/43/1b/5c431bb8-501e-4201-c3b1-c3fef5942f12/icon175x175.png

Tripcase:
- http://phonegap.com/app/tripcase/
- 2013-03-01-tripcase.md
* need to update our icon to the most current, here: http://a5.mzstatic.com/us/r30/Purple69/v4/3a/63/87/3a638719-0838-1214-711a-92bf1990825e/icon175x175.png

HealthTap
- http://phonegap.com/app/healthtap-find-doctors-and-free-answers/
- 2012-08-01-healthtap-find-doctors-and-free-answers.md

Hockey Community
- http://phonegap.com/app/hockey-community/
- 2012-05-08-hockey-community.html

Untappd
- http://phonegap.com/app/untappd/
- 2012-04-30-untappd.html
- * need to update our icon to the most current, here: http://a2.mzstatic.com/us/r30/Purple69/v4/59/7a/51/597a5159-2836-ab15-ef5a-d68978261460/icon175x175.png

Bit Timer
- http://phonegap.com/app/bit-timer/
- 2012-03-21-bit-timer.html
- need to update our icon to the most current, here: http://a2.mzstatic.com/us/r30/Purple7/v4/73/4d/6e/734d6e2b-050c-5d8e-4eb7-93953cd77fd0/icon175x175.jpeg

METAR Reader
- http://phonegap.com/app/metar-reader/
- 2011-09-23-metar-reader.html

Logitech Squeezebox™ Controller
- http://phonegap.com/app/logitech-squeezebox%E2%84%A2-controller-2/
- 2011-04-27-logitech-squeezeboxe284a2-controller-2.html

**Comment by GarthDB** [comment]
@jahoni thanks
