### ISSUE TITLE
Implement First Pass at Events Page

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#8]
Once the design is ready, we can implement the first pass at the events page.

**Comment by jahoni** [comment]
We need content

**Comment by jenlgray** [comment]
Come join us. We'd love to meet you!

PhoneGap Spain Meetup - February 24 - Barcelona, Spain
The 4YFN [4 Years From Now] congress, the home of the fast-growing tech startup community overall, will host our Phonegap Meetup in Barcelona during Mobile World Congress. A perfect setting to talk about design and user experience and basic concepts to consider when it comes to conceptualizing and developing your app. This is a great opportunity to catch up on what's new with PhoneGap and get the best tips on when and how to use push notifications to increase engagement with your users (and not disturb them). http://adobephonegapbarcelona.phonegapspain.com/ 

PhoneGap Day EU 2016 - May 19-20 - Amsterdam
Join PhoneGap and Cordova experts from around the world to hear what’s new in web and mobile development. Get the inside scoop on emerging frameworks and technologies and learn valuable tips and tricks to help with your next project. This is one of the best opportunities to network and learn from top industry leaders, meet with members of the PhoneGap team, hear the latest PhoneGap news, and find out what’s coming next! http://pgday.phonegap.com/eu2016/

**Comment by jahoni** [comment]
Created a [mock-up](https://www.dropbox.com/s/gjfctuxh68kcmxx/events.psd?dl=0) for the initial launch. 

Tried to keep it simple by replicating the style of the blog section on the homepage.

![events](https://cloud.githubusercontent.com/assets/178345/13157145/120726cc-d63b-11e5-95f9-a91fc6e3fdb6.png)

Made a couple of edits to the content:

Feb 24 2016
PhoneGap Spain Meetup
Barcelona, ES
The 4YFN [4 Years From Now] congress, the home of the fast-growing tech startup community overall, will host our Phonegap Meetup in Barcelona during Mobile World Congress. A perfect setting to talk about design and user experience and basic concepts to consider when it comes to conceptualizing and developing your app. This is a great opportunity to catch up on what's new with PhoneGap and get the best tips on when and how to use push notifications to increase engagement with your users (and not disturb them).

May 20 2016
PhoneGap Day EU 2016
Amsterdam, NL
Join PhoneGap and Cordova experts from around the world to hear what’s new in web and mobile development. With workshops on May 19 and the conference on May 20, you’ll get get the inside scoop on emerging frameworks and technologies and learn valuable tips and tricks to help with your next project. This is one of the best opportunities to network and learn from top industry leaders, meet with members of the PhoneGap team, hear the latest PhoneGap news, and find out what’s coming next!
