### ISSUE TITLE
Link to App Showcase in Global nav from Docs Site needs to be added

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#87]
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13186517/6954e584-d6fb-11e5-9824-6e6e25b01542.png)

Currently it doesn't link anywhere

**Comment by GarthDB** [comment]
I'll close that all up after I move to the new url - all of them are pointing to phonegap.github.io - I put all the changes in a pull request so I can be quick in fixing it. https://github.com/phonegap/phonegap.github.io/issues/87

**Comment by jahoni** [comment]
okay - it is pointing to http://docs.phonegap.com/# right now
