### ISSUE TITLE
Inconsistent columns in App Showcase

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/phonegap.github.io#96]
![image](https://cloud.githubusercontent.com/assets/21328/13191508/219889f8-d719-11e5-87d6-e2f35693c252.png)

- First row has 5
- Second row has 6
- Third row has 1

@jahoni is this design intentional? Otherwise, how many columns should be in a row?

**Comment by GarthDB** [comment]
@mwbrooks this is flexbox - it is a result of varied widths. I can fix them.

**Comment by jahoni** [comment]
not a design intent. ideally, the rows flow with columns "filling up" left to right.

**Comment by GarthDB** [comment]
I can tweak that with justify-content

**Comment by imhotep** [comment]
Facing this too!

**Comment by GarthDB** [comment]
This is fixed, but the filling up from left to right is an issue - I can't find a way to center the block of them if I'm filling up from left to right, so they will end up looking like this when the content doesn't fit perfectly:
![image](https://cloud.githubusercontent.com/assets/125516/13368952/dc2f23c4-dcac-11e5-8728-42eeb2d58979.png)

Let me know which you would prefer @jahoni

**Comment by GarthDB** [comment]
here's what it looks like now:
![image](https://cloud.githubusercontent.com/assets/125516/13368986/25b55202-dcad-11e5-9ba3-ec77c3d89bd5.png)

**Comment by jahoni** [comment]
I say left justified block. @mwbrooks and @imhotep do you concur?

**Comment by mwbrooks** [comment]
Yep, I think that feels right to me too @jahoni

**Comment by GarthDB** [comment]
:+1:
