### ISSUE TITLE
Anchor links on Product page should go to top of section/not cut off sub-titles

### ISSUE THREAD

**Issue by jahoni** [phonegap/phonegap.github.io#98]
http://phonegap.com/products/#desktop-app-section

Currently:
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13192856/44129c4c-d725-11e5-9d66-405c962b257f.png)

Would rather see:
![ssp_temp_capture](https://cloud.githubusercontent.com/assets/178345/13192898/b3ff7c6e-d725-11e5-8173-1da9fde000f4.png)

**Comment by GarthDB** [comment]
yeah

**Comment by jahoni** [comment]
just capturing it, not saying for today. creating a backlog of everything.
